In [16]:
from sklearn.linear_model import Perceptron
import numpy as np
import pandas as pd

In [5]:
x = [[0,0],[1,0],[0,1],[1,1]]
y = [0,1,1,1]

In [6]:
model = Perceptron()
model.fit(x,y)
model.score(x,y)

1.0

In [8]:
x1 = [[0.5,0],[0,0.5],[0.6,0]]
y1= model.predict(x1)

In [9]:
# Detail in cluster
y1

array([0, 0, 1])

In [11]:
x = [[-0.5,0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y = [1,1,0,0]

In [12]:
model = Perceptron()
model.fit(x,y)
model.score(x,y)

1.0

In [19]:
print("Hệ số intercept là: ", model.intercept_)
print('Hệ só coeffiient là: ',model.coef_)
print('Hệ số độ chính xác: ',model.score(x,y))

Hệ số intercept là:  [0.]
Hệ só coeffiient là:  [[-2.  -0.5]]
Hệ số độ chính xác:  1.0


# Iris

In [20]:
from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [28]:
iris = datasets.load_iris()

X = iris.data
y = iris.target


print(X[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [31]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.3)
SC = StandardScaler()
SC.fit(X_train)
X_train_std = SC.transform(X_train)

In [56]:
model = Perceptron(max_iter = 40, eta0 = 0.1, random_state = 0)
model.fit(X_train,y_train)
y_pred = model.predict(X_test)

print(y_pred)
print(y_test)
print('Độ chính xác mô hình chưa scale: ', accuracy_score(y_test,y_pred))

[1 2 1 1 0 2 0 0 0 1 1 0 1 0 1 0 1 2 1 2 2 2 0 1 2 2 2 1 1 1 2 1 2 1 1 0 0
 2 0 2 0 0 0 0 2]
[1 2 1 1 0 2 0 0 0 2 1 0 1 0 1 0 1 2 1 2 2 2 0 1 2 2 2 0 1 1 2 1 2 1 1 0 0
 2 0 2 0 0 0 0 2]
Độ chính xác mô hình chưa scale:  0.9555555555555556


In [57]:
SC = StandardScaler()
SC.fit(X_train)
X_test_std = SC.transform(X_test)

In [58]:
model = Perceptron(max_iter = 1000, eta0 = 0.1, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)

print(y_pred)
print(y_test)
print('Độ chính xác mô hình có scale: ', accuracy_score(y_test,y_pred))

[1 2 1 2 0 2 0 0 0 2 1 0 1 0 1 0 1 2 1 2 2 2 0 1 2 2 2 0 1 1 2 1 2 1 1 0 0
 2 0 2 0 0 0 0 2]
[1 2 1 1 0 2 0 0 0 2 1 0 1 0 1 0 1 2 1 2 2 2 0 1 2 2 2 0 1 1 2 1 2 1 1 0 0
 2 0 2 0 0 0 0 2]
Độ chính xác mô hình có scale:  0.9777777777777777


# Crabs

In [99]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn import datasets
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler

In [100]:
# Đọc data
url = 'crabs.csv'
data = pd.read_csv(url)
data.head()

speies sex  index  fontallip  rearwidth  length  width  depth
0      B   M      1        8.1        6.7    16.1   19.0    7.0
1      B   M      2        8.8        7.7    18.1   20.8    7.4
2      B   M      3        9.2        7.8    19.0   22.4    7.7
3      B   M      4        9.6        7.9    20.1   23.1    8.2
4      B   M      5        9.8        8.0    20.3   23.0    8.2

In [101]:
data.nunique()

speies         2
sex            2
index         50
fontallip    104
rearwidth     91
length       152
width        145
depth        102
dtype: int64

In [102]:
data['speies'].value_counts()

B    100
O    100
Name: speies, dtype: int64

In [103]:
data['sex'].value_counts()

M    100
F    100
Name: sex, dtype: int64

In [104]:
data['speies'] = data['speies'].map({'B': 0, 'O': 1})
data['sex'] = data['sex'].map({'M': 0, 'F': 1})

In [105]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   speies     200 non-null    int64  
 1   sex        200 non-null    int64  
 2   index      200 non-null    int64  
 3   fontallip  200 non-null    float64
 4   rearwidth  200 non-null    float64
 5   length     200 non-null    float64
 6   width      200 non-null    float64
 7   depth      200 non-null    float64
dtypes: float64(5), int64(3)
memory usage: 12.6 KB


In [106]:
data.corr()

speies           sex         index  fontallip  rearwidth  \
speies     1.000000e+00 -9.325873e-17  5.760810e-16   0.437966   0.315751   
sex       -9.325873e-17  1.000000e+00  1.957198e-16  -0.043309   0.291597   
index      5.760810e-16  1.957198e-16  1.000000e+00   0.862876   0.840040   
fontallip  4.379655e-01 -4.330897e-02  8.628756e-01   1.000000   0.906988   
rearwidth  3.157507e-01  2.915970e-01  8.400401e-01   0.906988   1.000000   
length     2.883330e-01 -1.049828e-01  9.114357e-01   0.978842   0.892743   
width      2.161801e-01 -7.443726e-02  9.282481e-01   0.964956   0.900402   
depth      4.237165e-01 -8.971958e-02  8.644594e-01   0.987627   0.889205   

             length     width     depth  
speies     0.288333  0.216180  0.423716  
sex       -0.104983 -0.074437 -0.089720  
index      0.911436  0.928248  0.864459  
fontallip  0.978842  0.964956  0.987627  
rearwidth  0.892743  0.900402  0.889205  
length     1.000000  0.995023  0.983204  
width      0.995023  1.000000  0.967812  
depth      0.983204  0.967812  1.000000

In [107]:
X = data.drop(['speies'], axis = 1)
y = data['speies']


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

SC = StandardScaler()
SC.fit(X_train)
X_train_std = SC.transform(X_train)
X_test_std = SC.transform(X_test)

In [111]:
model = Perceptron(max_iter = 100, eta0 = 0.1, random_state = 0)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)


print('Độ chính xác mô hình chưa scale: ', accuracy_score(y_test,y_pred))

Độ chính xác mô hình chưa scale:  0.975


# WIth 7 input and 1 output: `sex`

In [128]:
X = data.drop(['sex'], axis = 1)
y = data['sex']


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

SC = StandardScaler()
SC.fit(X_train)
X_train_std = SC.transform(X_train)
X_test_std = SC.transform(X_test)

In [146]:
model = Perceptron(max_iter = 10000, eta0 = 0.6, random_state = 4)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)


print('Độ chính xác mô hình scale: ', accuracy_score(y_test,y_pred))

Độ chính xác mô hình scale:  1.0


# Lung cancer

In [212]:
# Đọc data
url = 'lung_cancer_examples.csv'
data = pd.read_csv(url)
data.head()

Name      Surname  Age  Smokes  AreaQ  Alkhol  Result
0    John         Wick   35       3      5       4       1
1    John  Constantine   27      20      2       5       1
2  Camela     Anderson   30       0      5       2       0
3    Alex       Telles   28       0      8       1       0
4   Diego     Maradona   68       4      5       6       1

In [213]:
data = data.drop(['Name','Surname'],axis = 1)

In [214]:
data.head()

Age  Smokes  AreaQ  Alkhol  Result
0   35       3      5       4       1
1   27      20      2       5       1
2   30       0      5       2       0
3   28       0      8       1       0
4   68       4      5       6       1

In [215]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Age     59 non-null     int64
 1   Smokes  59 non-null     int64
 2   AreaQ   59 non-null     int64
 3   Alkhol  59 non-null     int64
 4   Result  59 non-null     int64
dtypes: int64(5)
memory usage: 2.4 KB


In [266]:
X = data.drop(['Result'], axis = 1)
y = data['Result']


X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

SC = StandardScaler()
SC.fit(X_train)
X_train_std = SC.transform(X_train)
X_test_std = SC.transform(X_test)

In [267]:
model = Perceptron(max_iter = 10000, eta0 = 0.03, random_state = 4)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)


print('Độ chính xác mô hình scale: ', accuracy_score(y_test,y_pred))

Độ chính xác mô hình scale:  0.9166666666666666


# Diabetes

In [285]:
# Đọc data
url = 'pima-indians-diabetes.csv'
data = pd.read_csv(url)
data.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [286]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 767 entries, 0 to 766
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   6       767 non-null    int64  
 1   148     767 non-null    int64  
 2   72      767 non-null    int64  
 3   35      767 non-null    int64  
 4   0       767 non-null    int64  
 5   33.6    767 non-null    float64
 6   0.627   767 non-null    float64
 7   50      767 non-null    int64  
 8   1       767 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [306]:
X = data.iloc[:, 0:-1]
y = data.iloc[:, -1]



X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.2)

SC = StandardScaler()
SC.fit(X_train)
X_train_std = SC.transform(X_train)
X_test_std = SC.transform(X_test)

In [307]:
model = Perceptron(max_iter = 10000, eta0 = 0.008, random_state = 4)
model.fit(X_train_std,y_train)
y_pred = model.predict(X_test_std)


print('Độ chính xác mô hình scale: ', accuracy_score(y_test,y_pred))

Độ chính xác mô hình scale:  0.7532467532467533
